# Generated by Django 4.1.1 on 2022-09-07 10:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_id_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b10baeb2-e39d-4893-b1e2-249b3badb771'), editable=False, primary_key=True, serialize=False),
        ),
    ]
