# Generated by Django 4.1.1 on 2022-09-07 10:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b21c4cb7-30c2-444a-a352-18da02bbeb83'), editable=False, primary_key=True, serialize=False),
        ),
    ]
