# Generated by Django 4.1.1 on 2022-09-07 14:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_id_alter_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ed96bf0c-5a27-4db9-a4f7-7e220d4451a3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
